# Generated by Django 5.1.4 on 2024-12-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
