# Generated by Django 5.1.4 on 2024-12-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_alter_author_born_location_alter_author_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
